# Generated by Django 4.2.6 on 2023-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_id_alter_book_id_alter_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=6, null=True),
        ),
    ]
