# Generated by Django 4.2.6 on 2023-10-29 10:43

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=books.models.generate_random_genre, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre'),
        ),
    ]
